name: Deploy Zap LoadBalancer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: zaplabwebsrv_1

    env:
      PRODUCTION_FOLDER: ${{ secrets.PRODUCTION_FOLDER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build project
        run: cargo build --release

      # - name: Run tests
      #   run: cargo test --verbose

      - name: Copy build to production folder
        if: success()
        run: |
          echo "Copying build artifacts to production folder"
          cp -r target/release/* $PRODUCTION_FOLDER
        - name: Post to a Slack channel
          id: slack
          uses: slackapi/slack-github-action@v1.27.0
          with:
            channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
            slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

# notify-on-failure:
#     if: failure()
#     runs-on: self-hosted
#     steps:
#       - name: Send failure notification
#         uses: dawidd6/action-send-mail@v3
#         with:
#           server_address: smtp.gmail.com
#           server_port: 465
#           username: ${{ secrets.SMTP_USERNAME }}
#           password: ${{ secrets.SMTP_PASSWORD }}
#           subject: Deploy zapLB fallito: ${{ github.workflow }}
#           body: |
#             L'action di deploy del zapLB (${{ github.workflow }}) ha fallito.
#             Controlla i log per maggiori dettagli.
#           to: ${{ secrets.EMAIL }}
#           from: ${{ secrets.EMAIL }}