name: Deploy Zap LoadBalancer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: zaplabwebsrv_1

    env:
      PRODUCTION_FOLDER: ${{ secrets.PRODUCTION_FOLDER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Post to Slack channel for starting build
        id: slack-start
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "Build started for ${{ github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Build project
        run: cargo build --release
        continue-on-error: true

      - name: Post to Slack channel for failed build
        if: ${{ failure() }}
        id: slack-fail-build
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "Build failed: ${{ github.event.head_commit.url }}\nError in build step."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Copy build to production folder
        if: ${{ success() }}
        run: |
          echo "Copying build artifacts to production folder"
          cp -r target/release/* $PRODUCTION_FOLDER
        continue-on-error: true

      - name: Post to Slack channel for failed copy
        if: ${{ failure() }}
        id: slack-fail-copy
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "Build succeeded, but copying to production folder failed: ${{ github.event.head_commit.url }}\nError in copy step."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Post to Slack channel for successful deployment
        if: ${{ success() }}
        id: slack-success
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "Build and deployment succeeded: ${{ github.event.head_commit.url }}\nArtifacts copied to production folder."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
